### ISSUE TITLE
Snaphot failes intermittenly at AWS Lambda

### ISSUE THREAD

**Issue by Notalifeform** [jeffreydwalter/arlo#44] opened 2018-02-09 14:49 UTC
I've build an Arlo  'snapshot' AWS lambda function, but is fails intermittently. 

What it does is create a TriggerFullFrameSnapshot every hour and stores it to S3. The first run always succeeds, but the next runs it (usually) fails to receive an event. I have been debugging it and it appears that the second run it returns directly here https://github.com/jeffreydwalter/arlo/blob/5956b1f3af30fdce7eea835aa3f9c6f250828aef/Arlo.py#L387 with an None event (it never blocks).

Apparently the  class is not completely stateless? My guess is that it does work when AWs spins up a new instance of the lambda function, but doesn't when AWS reuses an instance

I have not yet been able to reproduce it locally

I will dig into this further, but If anybody has an idea what is happening let me know...

The code below fails with the message

'Invalid URL 'None': No schema supplied. Perhaps you meant http://None?'

# code
```
def lambda_handler(event, context):
    print('Looking up sequence number')
    sequence = 0
    try:
        s3.Bucket(S3_BUCKET_NAME).download_file('sequence.txt', '/tmp/sequence.txt')
        with open('/tmp/sequence.txt', 'r') as myfile:
          data=myfile.read().replace('\n', '')
          sequence = int(data)
    except botocore.exceptions.ClientError as e:
        if e.response['Error']['Code'] == "404":
            print("Sequence file does not exist")
        else:
            raise
    sequence = sequence + 1 
    print('Creating ARLO snapshot {}'.format(sequence))
    try:
        arlo = Arlo(USERNAME, PASSWORD)
        basestations = arlo.GetDevices('basestation')

        print("BASE: {}".format(basestations))
        cameras = arlo.GetDevices('camera')

        print("CAMERA: {}".format(cameras))
        snapshot_url = arlo.TriggerFullFrameSnapshot(basestations[0], cameras[0])
        tag = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        filename = 'snapshot_{}_{}.jpg'.format(tag, "{:09d}".format(sequence))

        print('retrieving and storing  {}'.format(filename))
        arlo.DownloadSnapshot(snapshot_url, '/tmp/' + filename)
        data = open('/tmp/' + filename, 'rb')
        s3.Bucket(S3_BUCKET_NAME).put_object(Key=filename, Body=data)
        fh = open("/tmp/sequence.txt","w")
        fh.write(str(sequence))
        fh.close()
        data = open('/tmp/sequence.txt', 'rb')
        s3.Bucket(S3_BUCKET_NAME).put_object(Key='sequence.txt', Body=data)

        print('Script complete at {}'.format(str(datetime.now())))
    except Exception as e:
        print(e)

```

### version infp 

- python version: 3.6
- AWS lambda - not sure 
- pip3 freeze
 ```
arlo==1.0.2 (master)
certifi==2018.1.18
chardet==3.0.4
flake8==3.5.0
idna==2.6
mccabe==0.6.1
mockredispy==2.9.3
monotonic==1.4
pew==1.1.2
pipenv==9.0.3
pycodestyle==2.3.1
pyflakes==1.6.0
PySocks==1.6.8
redis==2.10.6
requests==2.18.4
six==1.11.0
sseclient==0.0.18
urllib3==1.22
virtualenv==15.1.0
virtualenv-clone==0.2.6

```
# Hardware

Arlo Pro
BASE: [{'userId': 'Q9V4H-257-31121171', 'deviceId': '4RD37B7KA00C5', 'uniqueId': 'xxx', 'deviceType': 'basestation', 'deviceName': 'xxx', 'lastModified': 1518186051062, 'firmwareVersion': '1.9.8.0_16666', 'xCloudId': 'xxx', 'userRole': 'OWNER', 'displayOrder': 3, 'mediaObjectCount': 0, 'state': 'provisioned', 'modelId': 'VMB4000', 'dateCreated': 1517688163998, 'interfaceVersion': 'i001', 'interfaceSchemaVer': '2', 'owner': {'firstName': 'xx', 'lastName': 'xx', 'ownerId': 'xx'}, 'properties': {'modelId': 'VMB4000', 'olsonTimeZone': 'Europe/Amsterdam', 'hwVersion': 'VMB4000r3'}, 'connectivity': {'type': 'ethernet', 'connected': True}}]

CAMERA: [{'userId': 'xx', 'deviceId': 'xx', 'parentId': 'xx', 'uniqueId': 'xx', 'deviceType': 'camera', 'deviceName': 'xx', 'lastModified': 1518186051083, 'firmwareVersion': '1.092.0.8_17203', 'xCloudId': 'xx', 'lastImageUploaded': 'true', 'userRole': 'OWNER', 'displayOrder': 1, 'presignedLastImageUrl': 'https://arlolastimage-z1.s3.amazonaws.com/xxxx/xxx/xx/lastImage.jpg?AWSAccessKeyId=xx&Expires=1518272451&Signature=xx', 'presignedSnapshotUrl': 'xx', 'presignedFullFrameSnapshotUrl': 'xx', 'mediaObjectCount': 0, 'state': 'provisioned', 'modelId': 'VMC4030', 'dateCreated': 1517688285880, 'interfaceVersion': 'i002', 'interfaceSchemaVer': '2', 'owner': {'firstName': 'xx', 'lastName': 'xx', 'ownerId': 'xx'}, 'properties': {'modelId': 'VMC4030', 'olsonTimeZone': 'Europe/Amsterdam', 'hwVersion': 'H11'}}]

**Comment by Notalifeform** [comment] 2018-02-09 16:22
locally it has the same issue if I wrap the code in a loop

```
import hello_lambda
import time

while True:
  hello_lambda.lambda_handler({"time": "2018-01-01"}, None)
  print('done. sleeping')
  time.sleep(1)
```

**Comment by jeffreydwalter** [comment] 2018-02-09 18:29
So, the Arlo API is built around a technology called EventStream. It was really designed for their web and mobile apps, and not for general scripting. As such, the EventStream is a stateful connection that acts similar to a websocket.

This library wraps the EventStream and provides a synchronous API, but under the hood it's subscribing to the EventStream in a thread when some methods are called. Some of the requests don't require the EventStream, and so they just make the HTTP request and return the response immediately. Others, make an HTTP request to the /notify endpoint, which triggers an asynchronous response via the EventStream. All of this is correlated using transaction ids.
The EventStream also requires a periodic keep-alive HTTP request to keep the EventStream open.

All that being said, I don't see how the library would be returning at line https://github.com/jeffreydwalter/arlo/blob/5956b1f3af30fdce7eea835aa3f9c6f250828aef/Arlo.py#L387 unless the timeout is occurring, which it really shouldn't in practice.
https://github.com/jeffreydwalter/arlo/blob/5956b1f3af30fdce7eea835aa3f9c6f250828aef/Arlo.py#L385-L400
If event was None, then the while loop would "continue" to the next iteration and none of the above code would execute.

Have you tried writing a simple version of your code taking AWS out of the loop (which I realize shouldn't matter), but would help to isolate the issue.

Can you give this a shot and see if it still fails?

```
def lambda_handler(event, context):
    print('Looking up sequence number')
    sequence = 0
    print('Creating ARLO snapshot {}'.format(sequence))
    try:
        arlo = Arlo(USERNAME, PASSWORD)
        basestations = arlo.GetDevices('basestation')

        print("BASE: {}".format(basestations))
        cameras = arlo.GetDevices('camera')

        print("CAMERA: {}".format(cameras))
        snapshot_url = arlo.TriggerFullFrameSnapshot(basestations[0], cameras[0])
        tag = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        filename = 'snapshot_{}_{}.jpg'.format(tag, "{:09d}".format(sequence))
        sequence = sequence + 1
        print('retrieving and storing  {}'.format(filename))
        arlo.DownloadSnapshot(snapshot_url, '/tmp/' + filename)
        print('Script complete at {}'.format(str(datetime.now())))
    except Exception as e:
        print(e)
```

**Comment by jeffreydwalter** [comment] 2018-02-09 18:35
Since you're instantiating the class over and over in a loop (which is not really how it was designed to be used) and making requests which cause a thread to be spun up for the EventStream,  I suppose there could be an issue with the thread from the previous instantiation of the library still being alive and connected to the EventStream.

**Comment by jeffreydwalter** [comment] 2018-02-09 19:15
What you probably need to do is call arlo.Logout() at the end of your loop.
https://github.com/jeffreydwalter/arlo/blob/5956b1f3af30fdce7eea835aa3f9c6f250828aef/Arlo.py#L225-L227

**Comment by Notalifeform** [comment] 2018-02-09 20:39
thx for chiming in

I  tried adding the arlo.Logout(), but it didn't help; right now I have the issue quite easily reproduced using the code below
(sometimes it breaks the 2nd snapshot, sometimes after the 10th)
The idea for me was to create a snapshot every 20 minutes, which should be ok for the API I guess.

```
import os
from datetime import datetime
from Arlo import Arlo
from pprint import pprint
import time


USERNAME = os.environ['ARLO_USERNAME']
PASSWORD = os.environ['ARLO_PASSWORD']

sequence = 0
def lambda_handler(event, context, sequence):
    print('Creating ARLO snapshot {}'.format(sequence))
    try:
        arlo = Arlo(USERNAME, PASSWORD)
        basestations = arlo.GetDevices('basestation')
        cameras = arlo.GetDevices('camera')
        snapshot_url = arlo.TriggerFullFrameSnapshot(basestations[0], cameras[0])
        tag = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
        filename = 'snapshot_{}_{}.jpg'.format(tag, "{:09d}".format(sequence))
        print('retrieving and storing  {}'.format(filename))
        arlo.DownloadSnapshot(snapshot_url, '/tmp/' + filename)
        print('Script complete at {}'.format(str(datetime.now())))
        arlo.Logout()
    except Exception as e:
        print(e)


while True:
  lambda_handler(None, None, sequence)
  sequence = sequence + 1
  print('done. sleeping')
  time.sleep(10)


```
output
 
```
Creating ARLO snapshot 4
retrieving and storing  snapshot_2018-02-09_21-31-54_000000004.jpg
Script complete at 2018-02-09 21:31:55.168550
done. sleeping
Creating ARLO snapshot 5
retrieving and storing  snapshot_2018-02-09_21-32-12_000000005.jpg
Script complete at 2018-02-09 21:32:12.915893
done. sleeping
Creating ARLO snapshot 6
retrieving and storing  snapshot_2018-02-09_21-32-30_000000006.jpg
Script complete at 2018-02-09 21:32:31.358783
done. sleeping
Creating ARLO snapshot 7
retrieving and storing  snapshot_2018-02-09_21-32-49_000000007.jpg
Script complete at 2018-02-09 21:32:50.053536
done. sleeping
Creating ARLO snapshot 8
retrieving and storing  snapshot_2018-02-09_21-33-05_000000008.jpg
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
done. sleeping
Creating ARLO snapshot 9
retrieving and storing  snapshot_2018-02-09_21-33-20_000000009.jpg
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
done. sleeping
^CCaught Ctrl-C, exiting.
```

**Comment by Notalifeform** [comment] 2018-02-09 22:16
What I see is that the class is leaking threads;  I added a 
`print("thread count: {}".format(threading.active_count()))` 
in the main loop to confirm this

maybe it's the  eventSource Thread?
The used eventsource library doesn't seem to have a 'close' option...

I the current state I can't use this lib on AWS lamda - which is a pity, because it is cheap :-) the available js libs (https://github.com/nevertheless75/node-arlo-api/) also seem quite rough.
So I guess for now the best option is to switch to EC2 (and run this script from cron)

**Comment by jeffreydwalter** [comment] 2018-02-10 03:10
That's helpful. If you stick with me, we'll get this issue resolved.

Can you print the name of the threads?
```
for thread in threading.enumerate():
    print(thread.name)
```

**Comment by jeffreydwalter** [comment] 2018-02-10 03:25
Looks like it's the EventStream thread, which is what I was saying earlier. When you instantiate the library over and over it doesn't kill the threads, for better or worse, since they are daemonized. They only die when the process dies.

```
python3 ArloTest.py 
thread count: 1
MainThread
Logged In
thread count: 3
MainThread
EventStream
HeartbeatThread
Logged In
thread count: 4
MainThread
EventStream
EventStream
HeartbeatThread
Logged In
thread count: 5
MainThread
EventStream
EventStream
EventStream
HeartbeatThread
Logged In
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

The good news is that it's trivial to reproduce, and we have definitive proof of what's going on. I should be able to get this resolved pretty quick. If you find a fix please do let me know.

**Comment by jeffreydwalter** [comment] 2018-02-10 06:43
@Notalifeform pushed a fix. You shouldn't need to call Logout() after this change, although it wouldn't hurt to.

Please let me know if you see any issues. Thanks!

**Comment by Notalifeform** [comment] 2018-02-10 10:35
@jeffreydwalter I can't reproduce the issue locally with your fix and deployed a new version to lambda - so far everything looks fine. I'm very grateful for your quick for this (and the library in general of course!)

**Closed as completed** 2018-02-10 10:35 UTC
Labels: bug, enhancement

**Comment by jeffreydwalter** [comment] 2018-02-10 16:21
@Notalifeform thanks for the feedback, beers (dontations) are welcome and appreciated. ;)

**Comment by jeffreydwalter** [comment] 2018-02-11 01:05
@Notalifeform thank you so much for your uber generous donation! I will be drinking my favorite Trappist ale, [Trappistes Rochefort 10](https://www.beeradvocate.com/beer/profile/207/645/) :D
